### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ohyeah521** [huuck/Katalina#2]
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from vm import VM
  File "/mnt/d/source_code/Python/Katalina/vm.py", line 4, in <module>
    from instructions import *
  File "/mnt/d/source_code/Python/Katalina/instructions.py", line 111
    match self.opcode:
          ^
SyntaxError: invalid syntax

wsl， python3.8

**Comment by huuck** [comment]
Hello! Please use Python 3.10 (earlier versions won't support matches). Also WSL support might be broken because of the logging feature. I'll add a JSON output that should fix this in the future.
